### ISSUE TITLE
Specialization constants

### ISSUE THREAD

**Issue by VeryOriginalNonsense** [sjb3d/caldera#1]
Hi,

I assume you're just sharing this project without an intent of making an "official" library, but it would be nice if specialization constants are supported. I implemented it myself in caldera, but I'm not making it a PR as I'm guessing you can make `p_specialization_info` in `PipelineShaderStageCreateInfo` (in spark) an option? At the moment it's a raw pointer.

I implemented it for myself & only for compute. I changed PipelineCache's get_compute and fixed dispatch_helper & compute app.
I utilized / tested it by changing a shader #define to `layout(constant_id = 0) const uint SEQUENCE_COUNT = 1024;`.

I might end up using this at least for a while, so thought I should make this a request.

Nice work by the way.

**Comment by sjb3d** [comment]
Hi, thanks for the comments.

Yep this is just a toy project at the moment, so I've no plans to publish this as a crate (or make any sort of guarantee about API stability etc!)

Specialization constants are a useful feature though, I'd be happy to add support for compute shaders as you described above.
